services:
  - type: web
    name: sustainable-energy-dashboard
    runtime: docker
    plan: starter
    repo: https://github.com/vrajpatell1/sustainable-energy
    branch: main
    autoDeployTrigger: commit
    healthCheckPath: /
    disk:
      name: sustainable-energy-db
      mountPath: /app/db
      sizeGB: 1
